[tool.poetry]
name = "contracts_service"
version = "0.2.0"
description = "Unicorn Properties Contact Service"
authors = ["Amazon Web Services"]
exclude = ["src/events/"]
packages = [{ include = "contracts_service", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.26.153"
aws-lambda-powertools = {extras = ["tracer"], version = "^2.16.2"}
aws-xray-sdk = "^2.12.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
coverage = "^6.4.2"
requests = "^2.31.0"
moto = "^3.1.17"
importlib-metadata = "^4.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -vv -W ignore::UserWarning --cov=contracts_service --cov-config=.coveragerc --cov-report term --cov-report html"
testpaths = [
    "./tests/unit",
    "./tests/integration",
]
