[tool.poetry]
name = "property_service"
version = "0.1.0"
description = "Unicorn Properties Property Service"
authors = ["Amazon Web Services"]
packages = [
    { include = "properties_service", from = "src" },
    { include = "schema", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.24.12"
aws-lambda-powertools = "^1.26.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
coverage = "^6.4.2"
requests = "^2.28.1"
moto = "^3.1.17"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -vv -W ignore::UserWarning --cov=properties --cov-config=.coveragerc --cov-report term --cov-report html"
testpaths = [
    "./tests/unit",
]
